### ISSUE TITLE
suggestion - Installation / setup

### ISSUE THREAD

**Issue by AruniRC** [NJNischal/Facial-Expression-Recognition-with-CNNs#1]
It would be good to have a setup.py or a requirements.txt for users of your codebase to set up quickly with the required dependencies. Otherwise, this is really cool!

**Comment by leodollinger** [comment]
> It would be good to have a setup.py or a requirements.txt for users of your codebase to set up quickly with the required dependencies. Otherwise, this is really cool!

Agree, i'm having problem running the code... always this error:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from camera import VideoCamera
  File "camera.py", line 6, in <module>
    model = FacialExpressionModel("model.json", "model_weights.h5")
  File "model.py", line 16, in __init__
    self.loaded_model._make_predict_function()
AttributeError: 'Sequential' object has no attribute '_make_predict_function'
```
Do you know how to solve it?
