### ISSUE TITLE
'Sequential' object has no attribute '_make_predict_function'

### ISSUE THREAD

**Issue by leodollinger** [NJNischal/Facial-Expression-Recognition-with-CNNs#2]
i'm having a problem running the code... always getting this error:

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from camera import VideoCamera
  File "camera.py", line 6, in <module>
    model = FacialExpressionModel("model.json", "model_weights.h5")
  File "model.py", line 16, in __init__
    self.loaded_model._make_predict_function()
AttributeError: 'Sequential' object has no attribute '_make_predict_function'
```

Can you help me?

**Comment by leodollinger** [comment]
For thoes with a similar problem, i fixed it by changing the "_make_predict_function" to "make_predict_function".
after fixing it, i had to change the video source on the camera.py __init__ function.

I'm on a Win 10, py 3.9.7, tensorflow 2.6.3 and 2.6.0
(if you have problems whith the tensorflow, this video helped me with it:
https://www.youtube.com/watch?v=xQVOaTUm9lM)
